### ISSUE TITLE
Better logging?

### ISSUE THREAD

**Issue by duijf** [svsticky/sadserver#170]
It is currently a bit involved to check our logs, as they are in random locations. At work, I can just `journalctl -eu <UNIT>` to see what's happening with that service

Maybe it is worth investigating changing our logging situation so stuff ends up in the journal?

Some concerns:

 - Do we care if our users can view the logs of their own websites? (Probably: yes)
 - Previous point probably means that the logs will be stored twice (once in the journal for our use and once in the homedirs). Is that a problem?
 - We probably want tagged log messages/structured logging so e.g. nginx access logs and error logs are still separate

Is this worth pursuing?

**Comment by tomwassenberg** [comment]
> Do we care if our users can view the logs of their own websites? (Probably: yes)

Are you talking specifically about nginx logs? Has there been a desire from a committee to be able to do this? Because while theoretically useful, there aren't many committees actively maintaining a (complex) website.

So I'm not sure yet that, might it be a lot of effort, it's worth it to adjust the setup specifically for committees. But I certainly agree that logging stuff to the journal will makes things easier for ourselves and that might be worth it all together.

**Comment by arianvp** [comment]
> Is this worth pursuing?
No
