### ISSUE TITLE
Implement photo gallery application

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/sadserver#174]
We need an alternative to Flickr, to host our "public" photos. Incomplete list of requirements:

- Access photo's from an object storage platform (probably S3 or Spaces)
- Show them in a gallery, with metadata like thumbnails etc.
- Only allow access after login with a Koala account (using Koala's OAuth support)

**Comment by duijf** [comment]
- Want to re-use a CDN like DO spaces or AWS S3 for the photos, and have it guard against enumeration attacks
 -

**Comment by martijncasteel** [comment]
Basically a flickr clone, it shouldn't be that hard. I started something small however discontinued it since the commit is willing to implement such an application. My advice would be to build it in rails since there is some experience there and use paperclip as well. 

- [ ] page showing albums
  - simple thumbail for landscape photos
  - thumbnail and crop portrait photos to landscape.
- [ ] page showing all photos of an album
- [ ] page showing selected image
  - ability to scroll thru images with gestures/arrows
- [ ] upload multiple files for administrators
  - create thumbnails but keep originals
- [ ] flag inappropriate images and hide them
- [ ] let administrators verify and remove inappropriate images 
- [ ] ask permission for tagging
  - no tagging of your person
  - tag yourself on images
  - let others tag you
- [ ] tag persons on images manually (fun things to add later on; recognizion of faces, suggesting a person, etc)
- [ ] add comments to photos on selected image page, flag them as well for administrators

**Comment by arianvp** [comment]
I would refrain from adding tagging functionality. As it complicates GDPR compliance

**Comment by emielvanrijn** [comment]
Several members said they would like to be able to see photos of activities within the corresponding activity in Koala. This would means we would have to change how activities are handled at the moment. But first, let me ask the million-dollar question, do we actually want this? If so, than activities should become visible even after attended (now hidden from regular users), but this means we should also hide the attendees list when an activity is displayed after the activity has taken place, because otherwise with a little deduction, it would be the same as tagging. Pros of this approach are that photos are clustered by activities, a user has already have to be logged in into koala to view the photos. Con is, that it is yet another feature in koala, and I know @martijncasteel isn't all to fond of these kind of features being added.

The other option we discussed was adding a photos section to svsticky.nl, where a member would have to OAuth with its koala account to get access to this restricted area on the website. Pros are that it would be quite a bit easier to maintain as it would be 'just' an extra seperate component to the list, and several React libraries exist for displaying photos nicely in grids and the like. Another pro is that a user that hasn't attended an activity is able to view photos of this activity, and thus can 'taste' the atmosphere.  Con is that it might be a little harder to match photos to activities, and that I am not aware of the current status of the OAuth and if this is easily doable.

Please let me know your comments, all of you :)!

**Comment by martijncasteel** [comment]
@emielvanrijn I think pictures would be a nice addition to koala. However this would probably require an overhaul of the membership pages. Still I think a refactor of currently functionality wouldn't be a bad idea. Perhaps make koala extensible with plugins (https://guides.rubyonrails.org/engines.html).

However file storage in rails doesn't has great support, the gem for file storage (https://robots.thoughtbot.com/closing-the-trombone) is deprecated and the new default from rails itself has bad support for authorization (and ugly url's).

**Comment by tomwassenberg** [comment]
There has been a photo application available for some time at https://photos.svsticky.nl/, without major issues, mostly thanks to @duijf. Closing this!
