### ISSUE TITLE
Certbot deployment issues and 18.04

### ISSUE THREAD

**Issue by arianvp** [svsticky/sadserver#178]
Tracking issue for the shenanigans of last meeting

**Comment by tomwassenberg** [comment]
I fixed all the stuff we encountered on `master` in the meantime, so it _should_ really work now.

The Certbot issue was due to Let's Encrypt not following redirects to IP-style URL's. They're [not gonna](https://github.com/letsencrypt/boulder/issues/3764) fix that, but at least the error will be more descriptive.

**Comment by tomwassenberg** [comment]
```
$ ssh svsticky.nl cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```
:tada:
