### ISSUE TITLE
Consolidate cert gathering

### ISSUE THREAD

**Issue by duijf** [svsticky/sadserver#180]
The current certificate request stuff leaves some things to be desired. We're starting to hit rate limits of Let'sEncrypt if we migrate the server because of the way we structure our subdomains.

The problem here is that we put most of the sites on `{{ cannonical_hostname }}`, because that helps with requesting staging certs.

We should evaluate if:

 - We want wildcard certs
 - We want to change our loop to put all websites in the Subject Alternative Names field (which @tomwassenberg thinks has a limit of ~100).

**Comment by tomwassenberg** [comment]
> We want to change our loop to put all websites in the Subject Alternative Names field (which @tomwassenberg thinks has a limit of ~100).

Source: https://letsencrypt.org/docs/rate-limits/#names-per-certificate

**Comment by tomwassenberg** [comment]
The [limit](https://letsencrypt.org/docs/rate-limits/#certificates-per-registered-domain) we had hit here has since been raised from 20 to 50, and we currently have 24 websites (== certs) defined. So we won't run into problems quickly, but we will when:

- we're migrating the production server, and
- at that moment we have >(50/2) websites, and
- the certs on the existing production server have all been renewed in the last seven days

The last condition can be easily prevented by disabling renewals a week in advance of the migration. 

We can still look at the abovementioned alternatives, but they won't be necessary until we have >50 websites.

**Comment by tomwassenberg** [comment]
We don't re-create the production server more than once or twice a year, and the mentioned workaround prevents the issue:
> The last condition can be easily prevented by disabling renewals a week in advance of the migration.

Therefore I'm closing this. Feel free to re-open if anyone deems this pressing anyway.
