### ISSUE TITLE
New execut redirect

### ISSUE THREAD

**Issue by duijf** [svsticky/sadserver#212]
Rob asked me if we could redirect qa.execut.nl -> https://app.sli.do/event/iefitsng/live

**Comment by RCdeWit** [comment]
Have another request as well:
feedback.execut.nl -> https://goo.gl/forms/tsFiesU04guc8dFb2

More generally: would it be possible to allow committee members to create subdomains on their own? @duijf explained it'd be difficult with permissions, but perhaps there's some way to make it work. Would also be valuable since there's a few outdated subdomains I'd like to make unavailable; right now my best option is to just have them redirect to the main domain.

**Comment by HugoPeters1024** [comment]
@RCdeWit Both redirects now are deployed since commit 66756028d40325873a7a4c5bb72fccd896505b72. Regarding subdomains for commissions, offline discussion suggested that this might be something for the future but not any time soon. "We will take it with"
